---
version: "3.11"

services:
  convert:
    build:
      context: .
      dockerfile: Dockerfile
    image: obsidian_speech_to_text_converter
    cap_drop: [ all ]
    cap_add: [ chown, setgid, setuid, kill ]
    volumes:
      - ./:/app
      - "${OSTTC_LOCAL_PATH:-./recordings}:/data"
      # if run locally, whisper stores models in ~/.cache/whisper
      - ./models:/root/.cache/whisper
    working_dir: /app
    entrypoint: python3 main.py